# Generated by Django 4.1.1 on 2022-11-03 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('chrom', models.CharField(max_length=100)),
                ('pos', models.IntegerField(default=0)),
                ('alt', models.CharField(max_length=100)),
                ('ref', models.CharField(max_length=100)),
                ('id', models.UUIDField(primary_key=True, serialize=False, unique=True)),
            ],
            options={
                'verbose_name': 'Data',
                'verbose_name_plural': 'Data',
                'db_table': 'Data',
            },
        ),
    ]
