# Generated by Django 4.1.3 on 2022-11-03 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_data_alt_alter_data_chrom_alter_data_filter_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='id_data',
            field=models.SlugField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='data',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='data',
            name='qual',
            field=models.SlugField(blank=True, max_length=1000, null=True),
        ),
    ]
