# Generated by Django 4.1.3 on 2022-11-06 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_data_id_data_alter_data_id_alter_data_qual'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='alt',
            field=models.SlugField(blank=True, max_length=100000, null=True),
        ),
        migrations.AlterField(
            model_name='data',
            name='chrom',
            field=models.SlugField(max_length=100000),
        ),
        migrations.AlterField(
            model_name='data',
            name='filter',
            field=models.SlugField(blank=True, max_length=100000, null=True),
        ),
        migrations.AlterField(
            model_name='data',
            name='format',
            field=models.SlugField(blank=True, max_length=100000, null=True),
        ),
        migrations.AlterField(
            model_name='data',
            name='id_data',
            field=models.SlugField(blank=True, max_length=100000),
        ),
        migrations.AlterField(
            model_name='data',
            name='info',
            field=models.SlugField(blank=True, max_length=100000, null=True),
        ),
        migrations.AlterField(
            model_name='data',
            name='nas',
            field=models.SlugField(blank=True, max_length=100000, null=True),
        ),
        migrations.AlterField(
            model_name='data',
            name='qual',
            field=models.SlugField(blank=True, max_length=100000, null=True),
        ),
        migrations.AlterField(
            model_name='data',
            name='ref',
            field=models.SlugField(blank=True, max_length=100000, null=True),
        ),
    ]
